# mode is either ircdocs or bare
mode: bare

# baseurl is where they'll be accessed
baseurl: '/devdocs'

# Files/Folders to exclude from the final output
exclude:
  - .sass-cache
  - CNAME
  - config.rb
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - CONTRIBUTING.md
  - index.html
  - assets

compress_html:
  clippings: []
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: [local]
  blanklines: true
  profile: false
  startings: []

sass:
  sass_dir: css

permalink: none

highlighter: rouge
markdown: kramdown

pregit: true  # pre-process to add git file times and commit ids
ghcommit: "https://github.com/irccom/devdocs/commit/"
ghrepo: "https://github.com/irccom/devdocs/blob/master/"
